### ISSUE TITLE
Unable to run the Hello World Test Case using MAK

### ISSUE THREAD

**Issue by manuelbeltranjr8** [IVCTool/IVCT_TestSuiteDevelopment#59]
Hi everyone,

I can not connect my TC Runner to the MAK Federation. Anyone can advise what I have done wrong or missed out in the configuration?

ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,537  TestEngine: TestEngine.onStartTestCase get TCInfo.testEngineLabel  "mak"
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,538  TestEngine: TestEngine.onStartTestCase get TCInfo.settingsDesignator ""
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,538  TestEngine: TestEngine is started for MAK RTI but possibly got wrong settingsDesignator  
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,538  TestEngine: Test Case Started: de.fraunhofer.iosb.tc_helloworld.TC0001
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,539  TestEngine$TestScheduleRunner: TestEngine:onMessageConsumer:run: de.fraunhofer.iosb.tc_helloworld.TC0001
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,539  TestEngine$TestScheduleRunner: TestEngine:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HelloWorld-2.1.2-SNAPSHOT/bin
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,539  TestEngine$TestScheduleRunner: TestEngine:onMessageConsumer:run: TC DIR is /root/application
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,539  TestEngine$TestScheduleRunner: TestEngine:onMessageConsumer:run: The test case class is: de.fraunhofer.iosb.tc_helloworld.TC0001
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,541  TestEngine$TestScheduleRunner: TestEngine.run.compabilityCheck: the IVCTVersion of testcase de.fraunhofer.iosb.tc_helloworld.TC0001@bf91872 is: 4.0.1-SNAPSHOT
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,541  AbstractTestCase: Test Case Started
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,541  AbstractTestCase: 
ivct-tc-runner-ma-1   | TEST CASE GLOBAL VARIABLES -------------------------------------- BEGIN
ivct-tc-runner-ma-1   | SUT Name: hw_iosb
ivct-tc-runner-ma-1   | SUT Federate Name: A
ivct-tc-runner-ma-1   | SUT Federation Name: HelloWorld
ivct-tc-runner-ma-1   | Engine Label: mak
ivct-tc-runner-ma-1   | Settings Designator: 
ivct-tc-runner-ma-1   | TEST CASE GLOBAL VARIABLES -------------------------------------- END
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,542  AbstractTestCase: 
ivct-tc-runner-ma-1   | TEST CASE PARAMETERS -------------------------------------- BEGIN
ivct-tc-runner-ma-1   | {"growthRate":"1.0003","SOMfile":"/root/conf/IVCTsut\/hw_iosb\/TS-HelloWorld-2019\/HelloWorld.xml"}
ivct-tc-runner-ma-1   | TEST CASE PARAMETERS -------------------------------------- END
ivct-tc-runner-ma-1   | Using MAK Technologies' RTI version 4.5f HLA 1516-2010 for GNU C++ version 4.8.5 20150623 (Red Hat 4.8.5-11).
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,543  TC0001: 
ivct-tc-runner-ma-1   | ---------------------------------------------------------------------
ivct-tc-runner-ma-1   | TEST PURPOSE
ivct-tc-runner-ma-1   | Test if a HelloWorld federate calculates a fixed population increase
ivct-tc-runner-ma-1   | correctly
ivct-tc-runner-ma-1   | Observe the federate for a fixed number of cycles and compare the
ivct-tc-runner-ma-1   | last received value with the previously received value plus the fixed
ivct-tc-runner-ma-1   | percentage and a small tolerance for each cycle
ivct-tc-runner-ma-1   | ---------------------------------------------------------------------
ivct-tc-runner-ma-1   | 
ivct-tc-runner-ma-1   | 
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,543  AbstractTestCase: TEST CASE PREAMBLE
ivct-tc-runner-ma-1   | 2023-08-31 08:57:59,543  TC0001: 
ivct-tc-runner-ma-1   | ---------------------------------------------------------------------
ivct-tc-runner-ma-1   | OPERATOR INSTRUCTIONS: 
ivct-tc-runner-ma-1   | 1. Start the test federate A and then hit confirm button
ivct-tc-runner-ma-1   | 2. The federate should run for the full duration of the tests
ivct-tc-runner-ma-1   | ---------------------------------------------------------------------
ivct-tc-runner-ma-1   | 
ivct-tc-runner-ma-1   | 
ivct-tc-runner-ma-1   | 2023-08-31 08:58:01,212  TestEngine: Testengine.onOperatorConfirmation get OperatorConfirmationInfo.testEngineLabel: mak
ivct-tc-runner-ma-1   | 2023-08-31 08:58:01,213  AbstractTestCase: OperatorConfirmation: true, Text: null
ivct-tc-runner-ma-1   | 2023-08-31 08:58:01,213  IVCT_BaseModel: initiateRTI: settingsDesignator is empty, using installation defaults
ivct-tc-runner-ma-1   | 2023-08-31 08:58:01,214  IVCT_RTIambassador: connect federateReference=de.fraunhofer.iosb.tc_lib.IVCT_LoggingFederateAmbassador@2ed47826, callbackModel=HLA_IMMEDIATE
ivct-tc-runner-ma-1   | Loading Config File: /tmp/rid.mtl
ivct-tc-runner-ma-1   | Received 1 messages that have an unknown or mismatching version.
ivct-tc-runner-ma-1   | Please verify that all federates are configured to use the same MAK RTI Version.
ivct-tc-runner-ma-1   | This message will repeat approximately every 5 minutes if the issue is not corrected or returns.
ivct-tc-runner-ma-1   | Failed to complete connection to the RTI Forwarder.
ivct-tc-runner-ma-1   | Failed to create a reliable connection to the RTI Forwarder. Please ensure that your connection parameters are configured correctly and that you have started the rtiexec or RTI Forwarder on the specified machine.
ivct-tc-runner-ma-1   | A reliable connection is required because RTI_internalMsgReliableWhenUsingRtiexec is enabled in your rid file (/tmp/rid.mtl).
ivct-tc-runner-ma-1   | Connection information:
ivct-tc-runner-ma-1   | Forwarder Address: 172.19.128.1
ivct-tc-runner-ma-1   | Port: 4001
ivct-tc-runner-ma-1   | TCP Network Interface: 172.19.128.1
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,233  IVCT_RTIambassador: connect exception=ConnectionFailed  Failed to create connection manager.
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,233  IVCT_BaseModel: initiateRti: 
ivct-tc-runner-ma-1   | hla.rti1516e.exceptions.ConnectionFailed: ConnectionFailed  Failed to create connection manager.
ivct-tc-runner-ma-1   |         at com.mak.makrti1516e.jni.DtJniRTIambassador.connect(Native Method)
ivct-tc-runner-ma-1   |         at com.mak.makrti1516e.DtRTIambassador.connect(DtRTIambassador.java:258)
ivct-tc-runner-ma-1   |         at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.connect(IVCT_RTIambassador.java:226)
ivct-tc-runner-ma-1   |         at de.fraunhofer.iosb.tc_lib.IVCT_BaseModel.initiateRti(IVCT_BaseModel.java:85)
ivct-tc-runner-ma-1   |         at de.fraunhofer.iosb.tc_helloworld.TC0001.preambleAction(TC0001.java:97)
ivct-tc-runner-ma-1   |         at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:214)
ivct-tc-runner-ma-1   |         at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:273)
ivct-tc-runner-ma-1   |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ivct-tc-runner-ma-1   |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ivct-tc-runner-ma-1   |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ivct-tc-runner-ma-1   |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ivct-tc-runner-ma-1   |         at java.lang.Thread.run(Thread.java:748)
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,234  IVCT_RTIambassador: getInteractionClassHandle theName=Communication
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,234  IVCT_RTIambassador: getInteractionClassHandle exception=NotConnected  Connection not established when calling getInteractionClassHandle
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,235  HelloWorldBaseModel: Cannot get interaction class handle or parameter handle
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,235  IVCT_RTIambassador: resignFederationExecution resignAction=DELETE_OBJECTS_THEN_DIVEST
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,235  IVCT_RTIambassador: resignFederationExecution exception=NotConnected  Connection not established when calling resignFederationExecution
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,236  IVCT_BaseModel: terminateRti: NotConnected (ignored)
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,236  AbstractTestCase: TC INCONCLUSIVE Cannot helloWorldBaseModel.init()
ivct-tc-runner-ma-1   | 2023-08-31 08:58:14,236  TestEngine$TestScheduleRunner: Test Case Ended

**Comment by manuelbeltranjr8** [comment]
I managed to resolve it by using the .yml file IVCT_Operation\vtmak\bridge-network\sut-helloworld\docker-compose-rtiexec.yml.

**Comment by manuelbeltranjr8** [comment]
It is confirmed rti version issue on different federates.
